package org.mlm.browkorftv.settings

import android.content.Context
import android.content.SharedPreferences
import android.os.Build
import androidx.datastore.preferences.core.*
import io.github.mlmgames.settings.core.SettingsRepository
import io.github.mlmgames.settings.core.datastore.createSettingsDataStore
import io.github.mlmgames.settings.core.managers.MigrationManager
import io.github.mlmgames.settings.core.managers.ResetManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.runBlocking
import org.mlm.browkorftv.utils.Utils

class SettingsManager private constructor(context: Context) {

    companion object {
        private const val DATASTORE_NAME = "app_settings"
        private const val OLD_PREFS_NAME = "main"

        @Volatile
        private var instance: SettingsManager? = null

        fun getInstance(context: Context): SettingsManager {
            return instance ?: synchronized(this) {
                instance ?: SettingsManager(context.applicationContext).also { instance = it }
            }
        }
    }

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    private val dataStore = createSettingsDataStore(context, DATASTORE_NAME)

    val repository = SettingsRepository(
        dataStore = dataStore,
        schema = AppSettingsSchema // Generated by KSP
    )

    val migrationManager = MigrationManager(dataStore, currentVersion = 1)
    val resetManager = ResetManager(dataStore, AppSettingsSchema)

    /** Main settings flow */
    val settings: Flow<AppSettings> = repository.flow

    /** Current settings value */
    val current: AppSettings get() = settingsState.value

    /** StateFlow for Compose/reactive usage */
    val settingsState: StateFlow<AppSettings> = settings
        .stateIn(scope, SharingStarted.Eagerly, AppSettings())

    val themeFlow: Flow<Theme> = settings.map { it.themeEnum }.distinctUntilChanged()
    val keepScreenOnFlow: Flow<Boolean> = settings.map { it.keepScreenOn }.distinctUntilChanged()
    val incognitoModeFlow: Flow<Boolean> = settings.map { it.incognitoMode }.distinctUntilChanged()
    val adBlockEnabledFlow: Flow<Boolean> =
        settings.map { it.adBlockEnabled }.distinctUntilChanged()
    val webEngineFlow: Flow<String> = settings.map { it.webEngine }.distinctUntilChanged()
    val searchEngineURLFlow: Flow<String> =
        settings.map { it.searchEngineURL }.distinctUntilChanged()
    val userAgentFlow: Flow<String?> = settings.map { it.effectiveUserAgent }.distinctUntilChanged()

    suspend fun update(transform: (AppSettings) -> AppSettings) {
        repository.update(transform)
    }

    suspend fun set(name: String, value: Any) {
        repository.set(name, value)
    }

    // Convenience setters for common operations
    suspend fun setTheme(theme: Theme) {
        update { it.copy(theme = theme.ordinal) }
    }

    suspend fun setKeepScreenOn(value: Boolean) {
        update { it.copy(keepScreenOn = value) }
    }

    suspend fun setIncognitoMode(value: Boolean) {
        update { it.copy(incognitoMode = value) }
    }

    suspend fun setSearchEngine(index: Int, customUrl: String? = null) {
        update { s ->
            var updated = s.copy(searchEngineIndex = index)
            if (customUrl != null) updated = updated.copy(searchEngineCustomUrl = customUrl)

            if (s.homePageModeEnum == HomePageMode.SEARCH_ENGINE) {
                val home = AppSettings.searchEngineHomeUrl(
                    index = updated.searchEngineIndex,
                    customSearchUrl = updated.searchEngineCustomUrl
                )
                updated = updated.copy(homePage = home)
            }
            updated
        }
    }

    suspend fun setHomePageProperties(mode: HomePageMode, customUrl: String? = null) {
        update { s ->
            val home = when (mode) {
                HomePageMode.SEARCH_ENGINE -> AppSettings.searchEngineHomeUrl(
                    index = s.searchEngineIndex,
                    customSearchUrl = s.searchEngineCustomUrl
                )

                HomePageMode.CUSTOM -> customUrl ?: AppSettings.HOME_URL_ALIAS
                HomePageMode.HOME_PAGE, HomePageMode.BLANK -> AppSettings.HOME_URL_ALIAS
            }
            s.copy(homePageMode = mode.ordinal, homePage = home)
        }
    }

    suspend fun setWebEngine(index: Int) {
        update { it.copy(webEngineIndex = index) }
    }

    suspend fun setAdBlockEnabled(enabled: Boolean) {
        update { it.copy(adBlockEnabled = enabled) }
    }

    suspend fun setAdBlockListLastUpdate(timestamp: Long) {
        update { it.copy(adBlockListLastUpdate = timestamp) }
    }

    suspend fun setIncognitoModeHintSuppress(value: Boolean) {
        update { it.copy(incognitoModeHintSuppress = value) }
    }

    suspend fun setAppVersionCodeMark(version: Int) {
        update { it.copy(appVersionCodeMark = version) }
    }

    suspend fun setNotificationAboutEngineChangeShown(version: Int) {
        update { it.copy(notificationAboutEngineChangeShown = version) }
    }

    suspend fun setInitialBookmarksSuggestionsLoaded(value: Boolean) {
        update { it.copy(initialBookmarksSuggestionsLoaded = value) }
    }

    private fun extractBaseUrl(url: String): String {
        val regex = """^https?://[^#?/]+""".toRegex()
        return regex.find(url)?.value ?: AppSettings.HOME_URL_ALIAS
    }


    suspend fun setUserAgent(index: Int, customUA: String? = null) {
        update { settings ->
            settings.copy(
                userAgentIndex = index,
                userAgentCustom = customUA
            )
        }
    }

    // Helper function (move to Utils ig)
    fun canRecommendGeckoView(context: Context): Boolean {
        val deviceRAM = Utils.memInfo(
            context
        ).totalMem
        val cpuHas64Bit = Build.SUPPORTED_64_BIT_ABIS.isNotEmpty()
        val cpuCores = Runtime.getRuntime().availableProcessors()
        val threeGB = 3_000_000_000L
        return deviceRAM >= threeGB && cpuHas64Bit && cpuCores >= 6
    }
}